package com.studycenter.dto;

import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class StudentRegisterRequest {

    // regNo is AUTO-GENERATED by the backend — not sent from frontend.

    @NotBlank(message = "name is required")
    private String name;

    private String fatherName;

    @NotBlank(message = "aadhaarNo is required")
    private String aadhaarNo;

    @NotBlank(message = "gender is required")
    private String gender;

    @NotBlank(message = "address is required")
    private String address;

    @NotBlank(message = "mobile is required")
    private String mobile;

    @NotBlank(message = "dateOfAdmission is required")
    private String dateOfAdmission;

    @NotBlank(message = "inTime is required")
    private String inTime;

    @NotBlank(message = "outTime is required")
    private String outTime;

    private BigDecimal admissionFee;
    private BigDecimal discountAmount;
    private String remarks;
}
